name: Patient Demographics API

services:
  performance-tests:
    build:
      dockerfile: ./dockerfiles/performance-tests/Dockerfile
      context: .
    volumes:
      - ./test-results/performance/:/test-results
    profiles:
      - tests

  unit-tests:
    build:
      dockerfile: ./dockerfiles/api/Dockerfile
      context: .
      target: build
    volumes:
      - ./test-results/unit/:/test-results
    command: >
      dotnet test test/unit/UnitTests.csproj --logger "trx;LogFileName=/test-results/test-results.trx"
    profiles:
      - tests

  api-contract-tests:
    build:
      dockerfile: ./dockerfiles/api/Dockerfile
      context: .
      target: build
    volumes:
      - ./test-results/api-contract/:/test-results
    command: >
      dotnet test test/api-contract/ApiContractTests.csproj --logger "trx;LogFileName=/test-results/test-results.trx"
    profiles:
      - tests

  api:
    build: 
      dockerfile: ./dockerfiles/api/Dockerfile
      context: .
      target: api
    ports:
      - 3000:8080
      
  api-documentation:
    build: 
      dockerfile: ./dockerfiles/documentation/Dockerfile
      context: .
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./documentation/api-documentation
        target: /docs
        read_only: true

  maintainer-documentation:
    build: 
      dockerfile: ./dockerfiles/documentation/Dockerfile
      context: .
    ports:
      - 8010:8000
    volumes:
      - type: bind
        source: ./documentation/maintainer-documentation
        target: /docs
        read_only: true
