name: Patient Demographics API

services:
  api:
    build: 
      dockerfile: ./dockerfiles/api/Dockerfile
      context: .
    ports:
      - 3000:8080
      
  api-documentation:
    build: 
      dockerfile: ./dockerfiles/documentation/Dockerfile
      context: .
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./documentation/api-documentation
        target: /docs
        read_only: true

  maintainer-documentation:
    build: 
      dockerfile: ./dockerfiles/documentation/Dockerfile
      context: .
    ports:
      - 8010:8000
    volumes:
      - type: bind
        source: ./documentation/maintainer-documentation
        target: /docs
        read_only: true
