site_name: Patient Demographics API Internal
site_url: http://localhost:8010/
theme:
  name: material

plugins:
  - search
  - panzoom:
      include_selectors:
        - ".mermaid"
      full_screen: true
      key: "ctrl"
  - awesome-nav:
      filename: .nav.yaml

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format